# function to retreive the corresponding query for each relation

from exception_classes import *

def find_relation(Property):
    """
    Probeert de passende relatie bij een bepaalde eigenschap te vinden. Gebruikt hiervoor zowel een basisset
    eigenschappen als een bestand met synoniemen, op basis waarvan eigenschappen kunnen worden verkregen.

    :param propert: de eigenschap als string.
    :return: de geschikte relatie als
    """
    relations = {
        "geboortedatum"     : "?identity dbpedia-owl:birthDate ?result",
        "naam"              : "?identity dbpedia-owl:longName ?result",
        "leden"             : "?identity dbpedia-owl:bandMember ?result",
        "genre"             : "{?identity dbpedia-owl:genre ?result} UNION {?identity prop-nl:stijl ?result}",
        "oorsprong"         : "?identity dbpedia-owl:origin ?result",
        "voormalige leden"  : "?identity dbpedia-owl:formerBandMember ?result",
        "bezetting"         : "?identity prop-nl:functie ?result",
        "overlijdensdatum"  : "?identity dbpedia-owl:deathDate ?result",
        "bijnaam"           : "{?identity prop-nl:bijnaam ?result} UNION {?identity foaf:nick ?result}",
        "uitgavedatum"      : "{?identity dbpedia-owl:releaseDate ?result} UNION {?identity prop-nl:releasedatum ?result}",
        "schrijvers"        : "?identity dbpedia-owl:writer ?result",
        "website"           : "?identity prop-nl:website ?result",
        "label"             : "?identity prop-nl:recordLabel ?result",
        "abstract"          : "?identity dbpedia-owl:abstract ?result",
        "albums"            : "?result rdf:type dbpedia-owl:Album. ?result prop-nl:artiest ?identity",
        "beginjaar"         : "?identity prop-nl:jarenActief ?result",
        "geloof"            : "{?identity prop-nl:geloof ?result} UNION {?identity prop-nl:religie ?result}",
        "schreef"           : "?identity dbpedia-owl:musicalArtist ?result",
        "waar geboren"      : "?identity dbpedia-owl:birthPlace ?result",
        "band"              : "{?identity dbpedia-owl:musicBand ?result} UNION {?identity dbpedia-owl:bandMember ?result}",
        "bezigheid"         : "{?identity dbpedia-owl:occupation ?result} UNION {?identity prop-nl:beroep ?result}",
        "duur"              : "?identity prop-nl:duur ?result",
        "doodsoorzaak"      : "?identity prop-nl:oorzaakDood ?result",
        "budget"            : "?identity prop-nl:budget ?result",
        "instrument"        : "{?identity prop-nl:instrument ?result} UNION {?identity prop-nl:instrumenten ?result}",
        "liedjes"           : "?identitys rdf:type dbpedia-owl:Single. ?identity dbpedia-owl:musicalArtist ?result",
        "artiest"           : "?identity prop-nl:artiest ?result",
        "manager"           : "?identity prop-nl:manager ?result",
        "partner"           : "?identity prop-nl:partner ?result",
        "producer"          : "?identity prop-nl:producer ?result",
        "kinderen"          : "?identity prop-nl:kinderen ?result",
        "land"              : "?identity prop-nl:land ?result",
    }

    subrelations = {
        "geboortedatum"     : "geboortedatum",
        "wanneer geboren"   : "geboortedatum",
        "verjaardag"        : "geboortedatum",
        "datum geboren"     : "geboortedatum",
        "geboortedag"       : "geboortedatum",
        "geboortejaar"      : "geboortedatum",
        "waar geboren"      : "waar geboren",
        "geboorteplaats"    : "waar geboren",
        "land geboren"      : "waar geboren",
        "stad geboren"      : "waar geboren",
        "dorpje geboren"    : "waar geboren",
        "plaats geboren"    : "waar geboren",
        "Nederlandse plaats geboren":"waar geboren",
        "volledige naam"    : "naam",
        "complete naam"     : "naam",
        "geboortenaam"      : "naam",
        "gehele naam"       : "naam",
        "artiest volledige naam": "naam",
        "naam"              : "naam",
        "echte naam"        : "naam",
        "hele naam"         : "naam",
        "echte/volledige naam": "naam",
        "namen"             : "naam",
        "leden"             : "leden",
        "bandleden"         : "leden",
        "leden band"        : "leden",
        "speelde"           : "leden",
        "namen leden"       : "leden",
        "bandlid"           : "leden",
        "huidige bandleden" : "leden",
        "lid"               : "leden",
        "personen band"     : "leden",
        "muziekstijl"       : "genre",
        "genre"             : "genre",
        "genres"            : "genre",
        "genre muziek"      : "genre",
        "genres muziek"     : "genre",
        "genres gerekend"   : "genre",
        "stijl muziek"      : "genre",
        "genre artiest(en)" : "genre",
        "genres nummers"    : "genre",
        "genre nummers"     : "genre",
        "genre(s) nummers"  : "genre",
        "genre(s) muziek"   : "genre",
        "stijl"             : "genre",
        "muzieksoort"       : "genre",
        "soort"             : "genre",
        "muziekstijl"       : "genre",
        "muziekstijlen"     : "genre",
        "genres toegeschreven muziek": "genre",
        "herkomst"          : "oorsprong",
        "waar herkomst"     : "oorsprong",
        "oorsprong"         : "oorsprong",
        "stad band"         : "oorsprong",
        "waar band"         : "oorsprong",
        "waar origineel"    : "oorsprong",
        "waar opgericht"    : "oorsprong",
        "waar"              : "oorsprong",
        "land oorsprong"    : "oorsprong",
        "waar oorsprong"    : "oorsprong",
        "stad opgericht"    : "oorsprong",
        "waar oorsprong"    : "oorsprong",
        "waar oprichting"   : "oorsprong",
        "herkomstplaats"    : "oorsprong",
        "roots"             : "oorsprong",
        "land"              : "land",
        "voormalige leden"  : "voormalige leden",
        "voormalige bandleden":"voormalige leden",
        "voormalige lid"    : "voormalige leden",
        "ex-leden"          : "voormalige leden",
        "ex-leden rockband" : "voormalige leden",
        "oudleden"          : "voormalige leden",
        "geweest lid"       : "voormalige leden",
        "bezetting"         : "bezetting",
        "functie"           : "bezetting",
        "functies"          : "bezetting",
        "samengesteld"      : "bezetting",
        "rollen"            : "bezetting",
        "overlijdensdatum"  : "overlijdensdatum",
        "wanneer overleden" : "overlijdensdatum",
        "dag overleden"     : "overlijdensdatum",
        "jaar overleden"    : "overlijdensdatum",
        "sterfdag"          : "overlijdensdatum",
        "sterfdatum"        : "overlijdensdatum",
        "sterfjaar"         : "overlijdensdatum",
        "bijnaam"           : "bijnaam",
        "bijnamen"          : "bijnaam",
        "wel genoemd"       : "bijnaam",
        "datum van uitgave" : "uitgavedatum",
        "uitgave datum"     : "uitgavedatum"  ,
        "uitgavedatum"       : "uitgavedatum"  ,
        "jaar single"       : "uitgavedatum" ,
        "schrijver"         : "schrijvers",
        "schrijvers"        : "schrijvers",
        "films muziek"      : "schrijvers",
        "site"              : "website",
        "URL"               : "website",
        "url"               : "website",
        "website"           : "website",
        "officiële website" : "website",
        "officiële website band" : "website",
        "officiele website" : "website",
        "website vinden informatie":"website",
        "dbtune website"    : "website",
        "label"             : "label",
        "recordlabel"       : "label",
        "recordlabels"      : "label",
        "muzieklabel"       : "label",
        "muzieklabel DJ"    : "label",
        "labels"            : "label",
        "uitgever"          : "label",
        "uitgevers"         : "label",
        "publisher"         : "label",
        "platenmaatschappij": "label",
        "platenmaatschappijen": "label",
        "platenmaatschappijen contract" : "label",
        "platenmaatschappijen gepubliceerd" : "label",
        "labels muziek uitgebracht" : "label",
        "platenlabel"       : "label",
        "record"            : "label",
        "abstract"          : "abstract",
        "samenvatting"      : "abstract",
        "platen"            : "albums",
        "plaat"             : "albums",
        "albums"            : "albums",
        "album"             : "albums",
        "albums uitgebracht": "albums",
        "albums uitgegeven" : "albums",
        "albums gemaakt"    : "albums",
        "album band"        : "albums",
        "debuut album"      : "albums",
        "debuutalbum"       : "albums",
        "langeste album"    : "albums",
        "beginjaar"         : "beginjaar",
        "wanneer begonnen"  : "beginjaar",
        "begin datum"       : "beginjaar",
        "wanneer opgericht" : "beginjaar",
        "begindatum"        : "beginjaar",
        "jaar band opgericht": "beginjaar",
        "jaar opgericht"    : "beginjaar",
        "wanneer band opgericht" : "beginjaar",
        "wanneer opgericht" : "beginjaar",
        "jaar"              : "beginjaar",
        "oprichtingsdatum"  : "beginjaar",
        "startdatum"        : "beginjaar",
        "startjaar"         : "beginjaar",
        "geloof"            : "geloof",
        "geloofsovertuiging": "geloof",
        "religie"           : "geloof",
        "schreef"           : "schreef",
        "geschreven"        : "schreef",
        "auteur"            : "schreef",
        "componist"         : "schreef",
        "liedje geschreven" : "schreef",
        "credits"           : "schreef",
        "band"              : "band",
        "bands"             : "band",
        "bezigheid"         : "bezigheid",
        "beroep"            : "bezigheid",
        "vak"               : "bezigheid",
        "beroepen"          : "bezigheid",
        "duur"              : "duur",
        "lengte"            : "duur",
        "duur/lengte"       : "duur",
        "doodsoorzaak"      : "doodsoorzaak",
        "oorzaak dood"      : "doodsoorzaak",
        "budget"            : "budget",
        "instrument"        : "instrument",
        "instrumenten"      : "instrument",
        "muziekinstrument"  : "instrument",
        "muziekinstrumenten": "instrument",
        "liedjes"           : "liedjes",
        "liedjes geproduceerd": "liedjes",
        "liedjes gemaakt"   : "liedjes",
        "single"            : "liedjes",
        "singles"           : "liedjes",
        "singles geproduceerd": "liedjes",
        "singles gemaakt"   : "liedjes",
        "liedje"            : "liedjes",
        "artiest"           : "artiest",
        "zanger"            : "artiest",
        "manager"           : "manager",
        "partner"           : "partner",
        "vrouw"             : "partner",
        "man"               : "partner",
        "producer"          : "producer",
        "kinderen"          : "kinderen"
    }

    relation = None
    try:
        relation = relations[subrelations[Property]]
    except KeyError:
        # TODO: Verkrijg relatie uit similarwords
        pass

    if not relation:
        raise NoPropertyRelationException
    return relation